baseURL        = "notasrandom.github.io"
title          = "Mis notas random"
languageCode   = "es-ar"
hasCJKLanguage = true
paginate       = 4
copyright      = "©2023"

[params]
  description = "Mis Notas"
  summaryLength = 70
    

[menu]
  [[menu.main]]
    identifier = "home"
    url        = "/"
    title      = "Home"
    weight     = 1

  [[menu.footer]]
    identifier = "github"
    url        = "https://github.com/undus5/hugo-pure"
    title      = "Github"
    weight     = 70
    [menu.footer.params]
      targetBlank = true
      iconClass   = "fa-brands fa-github"
  [[menu.footer]]
    identifier= "rss"
    url        = "/index.xml"
    title      = "RSS"
    weight     = 90
    [menu.footer.params]
      targetBlank = true
      iconClass   = "fa-solid fa-rss"
  [[menu.footer]]
    identifier = "search"
    url        = "/search/"
    title      = "Search"
    weight     = 999
    [menu.footer.params]
      targetBlank = false
      iconClass   = "fa-solid fa-magnifying-glass"


# Following configs need to be copied to the main site config

pluralizeListTitles = false

[markup]
  [markup.highlight]
    noClasses = true

# [outputFormats]
#   [outputFormats.jsentries]
#     baseName = "entries"
#     mediaType = "text/javascript"
#     
# [outputs]
#   home = ["html", "rss", "jsentries"]
